import 'package:core_erp/core/services/barcode_codec.dart';
import 'package:flutter_test/flutter_test.dart';

import 'fixtures/barcode_codec_vectors.dart';

/// The same codec exists in two languages, which is a real hazard: nothing stops
/// one side drifting from the other, and the symptom would be a printed label
/// the server refuses to resolve.
///
/// So the expectations here are not hand-written. They are generated by running
/// `backend/kernel/barcodes.js` itself. A mirror checked against hand-written
/// expectations only proves the two agree with whoever wrote them.

void main() {
  test('every generated encode vector matches the backend', () {
    expect(kEncodeVectors, isNotEmpty);
    for (final vector in kEncodeVectors) {
      expect(
        BarcodeCodec.encode(vector.type, vector.id),
        vector.code,
        reason: 'encode(${vector.type}, ${vector.id})',
      );
    }
  });

  test('every generated decode vector matches the backend', () {
    expect(kDecodeVectors, isNotEmpty);
    for (final vector in kDecodeVectors) {
      final decoded = BarcodeCodec.decode(vector.input);
      if (vector.isNull) {
        expect(decoded, isNull, reason: 'decode(${vector.input})');
        continue;
      }
      expect(decoded, isNotNull, reason: 'decode(${vector.input})');
      expect(decoded!.type, vector.type, reason: 'type of ${vector.input}');
      expect(decoded.id, vector.id, reason: 'id of ${vector.input}');
      expect(decoded.hasCheck, vector.hasCheck,
          reason: 'hasCheck of ${vector.input}');
      expect(decoded.checkValid, vector.checkValid,
          reason: 'checkValid of ${vector.input}');
    }
  });

  test('the vectors actually cover all 17 types', () {
    // A generated fixture is only as good as what was fed into the generator;
    // a vector set that quietly stopped covering a type would pass forever.
    final covered = <String>{
      for (final vector in kEncodeVectors)
        if (vector.code != null) vector.type.toUpperCase(),
    };
    expect(covered, hasLength(BarcodeCodec.types.length));
    expect(covered.difference(BarcodeCodec.types), isEmpty);
  });

  test('the vectors cover a failing check character, not just passing ones', () {
    // The check character is worthless if only valid codes were ever tested.
    expect(
      kDecodeVectors.any((v) => v.hasCheck == true && v.checkValid == false),
      isTrue,
    );
    expect(
      kDecodeVectors.any((v) => v.hasCheck == true && v.checkValid == true),
      isTrue,
    );
    expect(kDecodeVectors.any((v) => v.hasCheck == false), isTrue);
  });

  group('the properties the check character exists for', () {
    test('transposing two adjacent characters is caught', () {
      // An unweighted sum would not notice this, and transposition is the
      // commonest slip after a single wrong character.
      const id = 'REC-12-L1';
      final good = BarcodeCodec.encode('MAT', id)!;
      final transposed = good.replaceFirst('12', '21');
      expect(transposed, isNot(good));
      expect(BarcodeCodec.decode(transposed)!.checkValid, isFalse);
    });

    test('a code survives the whitespace a gun or a keyboard adds', () {
      final code = BarcodeCodec.encode('MAT', 'REC-1-L1')!;
      expect(BarcodeCodec.decode('  $code  ')!.checkValid, isTrue);
      expect(BarcodeCodec.decode(code.toLowerCase())!.checkValid, isTrue);
    });

    test('an unknown type encodes to nothing rather than to a lie', () {
      expect(BarcodeCodec.encode('NOPE', '1'), isNull);
      expect(BarcodeCodec.encode('MAT', '   '), isNull);
      expect(BarcodeCodec.decode('NOPE-1-X'), isNull);
    });

    test('canonicalOr falls back to the raw id rather than to nothing', () {
      // A label carrying a code that resolves by legacy fallback beats a label
      // carrying nothing.
      expect(BarcodeCodec.canonicalOr('MAT', 'ABC'), startsWith('MAT-ABC-'));
      expect(BarcodeCodec.canonicalOr('NOPE', 'ABC'), 'ABC');
    });
  });
}
