import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'package:core_erp/features/orders/domain/order_entry.dart';
import 'package:core_erp/features/orders/domain/order_inputs.dart';
import 'package:core_erp/features/orders/presentation/providers/orders_provider.dart';
import 'package:core_erp/features/delivery_challans/presentation/providers/delivery_challan_provider.dart';
import 'package:core_erp/features/delivery_challans/domain/delivery_challan.dart';
import 'package:core_erp/features/delivery_challans/data/delivery_challan_repository.dart';

class OrderFulfillmentPromptDialog extends StatefulWidget {
  const OrderFulfillmentPromptDialog({
    super.key,
    required this.order,
    required this.yieldProduced,
  });

  final OrderEntry order;
  final int yieldProduced;

  @override
  State<OrderFulfillmentPromptDialog> createState() =>
      _OrderFulfillmentPromptDialogState();
}

class _OrderFulfillmentPromptDialogState
    extends State<OrderFulfillmentPromptDialog> {
  bool _isProcessing = false;

  Future<void> _completeOrder() async {
    if (_isProcessing) return;
    setState(() => _isProcessing = true);

    try {
      await context
          .read<OrdersProvider>()
          .updateOrderLifecycle(UpdateOrderLifecycleInput(id: widget.order.id, status: OrderStatus.completed));
      if (!mounted) return;
      Navigator.of(context).pop();
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Order marked as completed!'),
          backgroundColor: Color(0xFF16A34A),
        ),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Failed to complete order: $e'),
          backgroundColor: const Color(0xFFDC2626),
        ),
      );
    } finally {
      if (mounted) setState(() => _isProcessing = false);
    }
  }

  Future<void> _draftChallan() async {
    if (_isProcessing) return;
    setState(() => _isProcessing = true);

    try {
      final challanProvider = context.read<DeliveryChallanProvider>();
      
      final input = DeliveryChallanDraftInput(
        type: ChallanType.delivery,
        purpose: ChallanPurpose.trading,
        challanNo: '', // Auto-generated by backend usually
        orderId: widget.order.id,
        orderIds: [widget.order.id],
        vendorId: 0,
        date: DateTime.now(),
        location: 'Main Factory',
        sourceReference: 'Production Yield',
        notes: 'Generated from Production Floor',
        maintainStocks: true,
        customerName: widget.order.clientName,
        customerGstin: '',
        vendorName: '',
        vendorGstin: '',
        items: [
          DeliveryChallanItem(
            id: 0,
            orderItemId: null,
            productionRunId: null,
            itemId: widget.order.itemId,
            variationLeafNodeId: widget.order.variationLeafNodeId,
            lineNo: 1,
            particulars: widget.order.itemName,
            hsnCode: '',
            variationPathLabel: widget.order.variationPathLabel,
            note: 'Yield Production Delivery',
            quantityPcs: widget.yieldProduced.toString(),
            weight: '',
          )
        ],
      );

      final challan = await challanProvider.createChallan(input);

      if (!mounted) return;
      Navigator.of(context).pop();

      if (challan != null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Delivery Challan drafted successfully!'),
            backgroundColor: Color(0xFF16A34A),
          ),
        );
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Failed to draft challan: $e'),
          backgroundColor: const Color(0xFFDC2626),
        ),
      );
    } finally {
      if (mounted) setState(() => _isProcessing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final order = widget.order;
    final totalDelivered = order.totalDeliveredQty;
    final totalNow = totalDelivered + widget.yieldProduced;
    final progress = (totalNow / order.quantity).clamp(0.0, 1.0);
    final isFulfilled = totalNow >= order.quantity;

    return Dialog(
      backgroundColor: const Color(0xFF18181B),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Container(
        width: 500,
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(
                  isFulfilled ? Icons.check_circle : Icons.info,
                  color: isFulfilled
                      ? const Color(0xFF22C55E)
                      : const Color(0xFF3B82F6),
                  size: 28,
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    isFulfilled ? 'Order Fulfilled!' : 'Order Progress',
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.close, color: Color(0xFFA1A1AA)),
                  onPressed: _isProcessing ? null : () => Navigator.of(context).pop(),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Text(
              'Run Yield: ${widget.yieldProduced} ${order.unitDisplayLabel}',
              style: const TextStyle(
                color: Color(0xFFE4E4E7),
                fontSize: 16,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Order ${order.orderNo} for ${order.clientName} requires ${order.quantity} ${order.unitDisplayLabel}.',
              style: const TextStyle(
                color: Color(0xFFA1A1AA),
                fontSize: 14,
              ),
            ),
            const SizedBox(height: 24),
            ClipRRect(
              borderRadius: BorderRadius.circular(8),
              child: LinearProgressIndicator(
                value: progress,
                minHeight: 12,
                backgroundColor: const Color(0xFF27272A),
                color: isFulfilled
                    ? const Color(0xFF22C55E)
                    : const Color(0xFF3B82F6),
              ),
            ),
            const SizedBox(height: 12),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  '${totalNow.toInt()} / ${order.quantity} delivered',
                  style: const TextStyle(
                    color: Color(0xFFA1A1AA),
                    fontSize: 13,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                Text(
                  '${(progress * 100).toStringAsFixed(1)}%',
                  style: const TextStyle(
                    color: Color(0xFFA1A1AA),
                    fontSize: 13,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 32),
            Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                OutlinedButton(
                  style: OutlinedButton.styleFrom(
                    foregroundColor: const Color(0xFFE4E4E7),
                    side: const BorderSide(color: Color(0xFF3F3F46)),
                    padding: const EdgeInsets.symmetric(
                      horizontal: 16,
                      vertical: 16,
                    ),
                  ),
                  onPressed: _isProcessing ? null : _completeOrder,
                  child: const Text('Mark Completed'),
                ),
                const SizedBox(width: 12),
                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF3B82F6),
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(
                      horizontal: 20,
                      vertical: 16,
                    ),
                  ),
                  onPressed: _isProcessing ? null : _draftChallan,
                  icon: _isProcessing
                      ? const SizedBox(
                          width: 16,
                          height: 16,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : const Icon(Icons.local_shipping_outlined, size: 20),
                  label: Text(
                    _isProcessing ? 'Processing...' : 'Draft Delivery Challan',
                    style: const TextStyle(fontWeight: FontWeight.bold),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
