import 'package:flutter/foundation.dart';

/// The client-side half of the universal barcode codec.
///
/// A mirror of `backend/kernel/barcodes.js`. Duplicated logic across two
/// languages is a genuine hazard, so it is kept honest from the outside: the
/// test vectors in `test/fixtures/barcode_codec_vectors.dart` are *generated by
/// running the real backend implementation*, not written by hand. A mirror
/// checked against hand-written expectations only proves the two agree with
/// whoever wrote them; checked against generated vectors, drift on either side
/// fails loudly.
///
/// This exists so the desktop can put a **canonical** code on a label. Printing
/// the raw stored id instead still scans — the resolver falls back to the legacy
/// columns — but it resolves unverified, with no check character, and the
/// inspector then has to say so. A freshly printed label should not be born
/// legacy.
@immutable
class DecodedBarcode {
  const DecodedBarcode({
    required this.type,
    required this.id,
    required this.hasCheck,
    required this.checkValid,
  });

  final String type;
  final String id;

  /// Whether a check character was present at all. False for a hand-typed or
  /// legacy code, which still resolves — just unverified.
  final bool hasCheck;

  /// False only when a check character was present and did not match.
  final bool checkValid;
}

class BarcodeCodec {
  const BarcodeCodec._();

  static const String checkAlphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';

  /// The entity types, mirroring `TYPES` in the kernel. Order is irrelevant;
  /// membership is not — an unknown type must encode to null rather than to a
  /// code that names nothing.
  ///
  /// `LOC` and `FLR` are places, and unlike the rest they are not backed by a
  /// table of records — a location is a free-text string on a stock position, a
  /// floor is one on a machine. That only changes how the server resolves them;
  /// the codec treats them like any other type.
  static const Set<String> types = <String>{
    'MAT', 'DC', 'RC', 'DCL', 'ORD', 'RUN', 'MFG', 'EMP', 'DEP',
    'PLN', 'CLI', 'VEN', 'MCH', 'DIE', 'ITM', 'GRP', 'MOV',
    'LOC', 'FLR',
  };

  static final RegExp _whitespace = RegExp(r'\s+');

  /// Uppercase, whitespace removed.
  ///
  /// Scanner guns and phone keyboards both introduce stray space, and a code
  /// that fails to resolve because of a space nobody can see is
  /// indistinguishable from a code that does not exist.
  static String normalize(String? code) =>
      (code ?? '').replaceAll(_whitespace, '').trim().toUpperCase();

  /// One character derived from everything before it, weighted by position so
  /// that transposing two adjacent characters changes the result. An unweighted
  /// sum would not, and transposition is the commonest slip after a wrong digit.
  static String checkCharacter(String payload) {
    final text = normalize(payload);
    var total = 0;
    for (var i = 0; i < text.length; i += 1) {
      total += text.codeUnitAt(i) * (i + 1);
    }
    return checkAlphabet[total % checkAlphabet.length];
  }

  /// The barcode for an entity, or null when the type is unknown or the id is
  /// empty — a code that names nothing is worse than no code.
  static String? encode(String type, String id) {
    final upperType = normalize(type);
    if (!types.contains(upperType)) return null;
    final value = normalize(id);
    if (value.isEmpty) return null;
    final payload = '$upperType-$value';
    return '$payload-${checkCharacter(payload)}';
  }

  /// Reads a code back to the entity it names, or null when it is not one of
  /// ours.
  static DecodedBarcode? decode(String? code) {
    final text = normalize(code);
    if (text.isEmpty) return null;

    final parts = text.split('-');
    if (parts.length < 2) return null;

    final type = parts.first;
    if (!types.contains(type)) return null;

    // A trailing single character *may* be the check. It may equally be the end
    // of an id that happens to finish in one character after a dash. Decide by
    // testing it rather than by assuming.
    final last = parts.last;
    if (parts.length > 2 && last.length == 1) {
      final payload = parts.sublist(0, parts.length - 1).join('-');
      final id = parts.sublist(1, parts.length - 1).join('-');
      // A single trailing character that is not the right check is a misread,
      // not part of the id — reporting that is the whole point of having one.
      return DecodedBarcode(
        type: type,
        id: id,
        hasCheck: true,
        checkValid: checkCharacter(payload) == last,
      );
    }

    return DecodedBarcode(
      type: type,
      id: parts.sublist(1).join('-'),
      hasCheck: false,
      checkValid: true,
    );
  }

  /// Whether a string looks like one of ours at all. For choosing between the
  /// structured path and a legacy search, not for validation.
  static bool isStructured(String? code) => decode(code) != null;

  /// The canonical code for an id already stored on a record, falling back to
  /// the raw id when the type is unknown.
  ///
  /// The fallback matters: a label is better carrying a code that resolves by
  /// legacy fallback than carrying nothing at all.
  static String canonicalOr(String type, String id) => encode(type, id) ?? id;
}
