'use strict';

// ---------------------------------------------------------------------------
// Scenario: "Established Business · One Year".
//
// Sarvadnya Udyog has been on the software for eleven months. This seeder lays
// down what that actually leaves behind: a staffed factory with machines and
// dies on the floor, a client book that grew from two names to six, orders
// that ramp month over month, production runs against real pipelines, delivery
// and reception challans, eleven closed payroll cycles, and the paper trail
// each of those drags along.
//
// Written in foreign-key order (see the Dependency Atlas): every phase below
// only references rows an earlier phase created. Deterministic — a fixed PRNG
// seed means reseeding twice produces byte-identical data, so tests can pin
// numbers to it.
// ---------------------------------------------------------------------------

/** Deterministic PRNG (mulberry32). Same seed → same factory, every time. */
function makeRng(seed) {
  let a = seed >>> 0;
  return function rng() {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const MONTHS_OF_HISTORY = 11;

module.exports = async function seedEstablishedYear(ctx) {
  try {
    return await seedInner(ctx);
  } catch (e) {
    if (typeof e.__phase === 'undefined') throw e;
    throw e;
  }
};

async function seedInner(ctx) {
  // eslint-disable-next-line no-unused-vars
  const _phaseTrap = true;
  const { get, all, run } = ctx;
  const rng = makeRng(20260816);
  const pick = (arr) => arr[Math.floor(rng() * arr.length)];
  const between = (lo, hi) => lo + Math.floor(rng() * (hi - lo + 1));

  // Anchor the whole story to today so it always reads as "the last year".
  const today = new Date();
  const startOfHistory = new Date(today);
  startOfHistory.setMonth(startOfHistory.getMonth() - MONTHS_OF_HISTORY);
  /** Nothing in a history may be dated later than today. */
  const clamp = (d) => (d.getTime() > today.getTime() ? new Date(today) : d);
  const iso = (d) => clamp(d).toISOString();
  const day = (d) => clamp(d).toISOString().slice(0, 10);
  /** A date `monthsAgo` back, on `dayOfMonth`. */
  const at = (monthsAgo, dayOfMonth, hour = 10) => {
    const d = new Date(today);
    d.setMonth(d.getMonth() - monthsAgo);
    d.setDate(Math.min(dayOfMonth, 28));
    d.setHours(hour, between(0, 59), 0, 0);
    return d;
  };
  const stamp = iso(today);

  // Master imagery generated by tools/generate-seed-images.py and served from
  // backend/public. Absolute because the clients render photos with
  // Image.network, which will not resolve a bare path; the host matches the
  // app's PAPER_API_BASE_URL default.
  const IMAGE_BASE = (process.env.PAPER_PUBLIC_BASE_URL
    || 'http://localhost:8080').replace(/\/$/, '') + '/public/seed';
  const imageSlug = (name) => String(name)
    .split('')
    .map((c) => (/[a-z0-9]/i.test(c) ? c.toLowerCase() : '-'))
    .join('')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48);
  /// Every seeded master gets a picture — a catalogue with half its tiles
  /// showing initials reads as unfinished.
  const photoFor = (domain, name) =>
    `${IMAGE_BASE}/${domain}-${imageSlug(name)}.png`;

  const summary = {};
  /// Whether this order line got a production run, which decides if a
  /// pipeline-assignment activity entry is truthful for it.
  const runByOrderId = new Set();
  const if_pipeline = (order) => runByOrderId.has(order.id);
  const countOf = async (t) =>
    (await get(`SELECT COUNT(*) AS n FROM ${t}`))?.n ?? 0;

  // A fresh database carries fewer tables and columns than a long-lived dev one
  // — the payroll and leave tables in particular only exist where an older
  // migration path created them. Probe rather than assume, and record what got
  // skipped instead of failing the whole reset over an absent subsystem.
  const skipped = [];
  // Long seeder: name each phase as it starts so a constraint failure is
  // attributable without a stack trace.
  let currentPhase = 'init';
  const phase = (label) => {
    currentPhase = label;
    if (process.env.SEED_TRACE) console.log('  [seed] phase:', label);
  };
  const named = (e) => { e.message = `[phase: ${currentPhase}] ${e.message}`; return e; };
  const tableExists = async (t) =>
    Boolean(await get(
      "SELECT name FROM sqlite_master WHERE type='table' AND name = ?", [t]));

  // ── Phase 1 · The people (L0) ────────────────────────────────────────────
  phase('The people');
  // employees is the single biggest dead hub — 7 tables hang off it.
  const DEPARTMENTS = [
    ['Press Shop', 'Blanking, piercing and forming lines'],
    ['Assembly', 'Sub-assembly, riveting and final fitting'],
    ['Quality & Dispatch', 'Inspection, packing and outward challans'],
    ['Maintenance', 'Die upkeep, machine servicing and tool room'],
    ['Accounts & Admin', 'Payroll, procurement and compliance'],
  ];
  const deptIds = {};
  for (const [name, description] of DEPARTMENTS) {
    const r = await run(
      `INSERT INTO departments
         (name, description, photo_url, is_archived, created_at, updated_at)
       VALUES (?, ?, ?, 0, ?, ?)`,
      [name, description, photoFor('department', name), iso(startOfHistory), stamp],
    );
    deptIds[name] = r.lastID;
  }

  const STAFF = [
    ['Ramesh Kulkarni', 'Press Shop', 'Shift Supervisor', 'full_time'],
    ['Sunil Pawar', 'Press Shop', 'Press Operator', 'full_time'],
    ['Ganesh Shinde', 'Press Shop', 'Press Operator', 'full_time'],
    ['Vikas More', 'Press Shop', 'Helper', 'contract'],
    ['Anita Deshmukh', 'Assembly', 'Line Lead', 'full_time'],
    ['Sonal Jadhav', 'Assembly', 'Assembly Operator', 'full_time'],
    ['Priya Salunke', 'Assembly', 'Assembly Operator', 'full_time'],
    ['Kavita Bhosale', 'Assembly', 'Assembly Operator', 'contract'],
    ['Mahesh Gaikwad', 'Quality & Dispatch', 'QC Inspector', 'full_time'],
    ['Nitin Chavan', 'Quality & Dispatch', 'Dispatch Clerk', 'full_time'],
    ['Sachin Patil', 'Maintenance', 'Tool Room Fitter', 'full_time'],
    ['Amit Jagtap', 'Maintenance', 'Maintenance Technician', 'full_time'],
    ['Deepa Kale', 'Accounts & Admin', 'Accounts Executive', 'full_time'],
    ['Rohit Sawant', 'Accounts & Admin', 'Stores & Purchase', 'full_time'],
  ];
  const employees = [];
  for (let i = 0; i < STAFF.length; i += 1) {
    const [name, dept, role, employment] = STAFF[i];
    // Staggered joining dates — the floor was hired up over the first months.
    const joined = at(MONTHS_OF_HISTORY - Math.min(i % 6, MONTHS_OF_HISTORY - 1), 3 + (i % 20));
    const r = await run(
      `INSERT INTO employees
         (department_id, name, role, phone, address, employee_photo_url,
          employment_type, status, barcode_id, is_archived, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, 'active', ?, 0, ?, ?)`,
      [
        deptIds[dept], name, role,
        `+9198${String(20000000 + i * 137717).slice(0, 8)}`,
        `${pick(['Bhosari', 'Chinchwad', 'Nigdi', 'Akurdi', 'Pimpri'])}, Pune`,
        photoFor('employee', name),
        employment,
        `EMP-${String(1001 + i)}`,
        iso(joined), stamp,
      ],
    );
    employees.push({ id: r.lastID, name, dept, role, employment });
  }

  // ── Phase 2 · The floor: machines and dies (L0) ──────────────────────────
  phase('The floor: machines and dies');
  // Pipeline node fixtures already name these; without the masters every stage
  // opened "Unassigned".
  const MACHINES = [
    ['Power Press 60T', 'PP-60T-01', 'Rack A1', 'Press Shop floor', 1800, 25, 2, 7.5],
    ['Power Press 100T', 'PP-100T-02', 'Rack A2', 'Press Shop floor', 1200, 40, 2, 11],
    ['Cutter 04', 'CUT-04', 'Cutting bay', 'Press Shop floor', 2400, 15, 1, 3.7],
    ['Hydraulic Press 150T', 'HP-150T-05', 'Rack B1', 'Press Shop floor', 900, 55, 3, 15],
    ['Riveting Station 1', 'RIV-01', 'Assembly line 1', 'Assembly hall', 3000, 10, 1, 1.5],
    ['Riveting Station 2', 'RIV-02', 'Assembly line 2', 'Assembly hall', 3000, 10, 1, 1.5],
    ['Polishing Barrel', 'POL-01', 'Finishing bay', 'Assembly hall', 1500, 30, 1, 5.5],
    ['Weld Station A', 'WLD-A', 'Join bay', 'Press Shop floor', 700, 20, 2, 9],
  ];
  const machines = [];
  for (const [name, assetId, location, area, perHour, setup, labor, kw] of MACHINES) {
    const r = await run(
      `INSERT INTO machines
         (name, asset_id, primary_photo_url, make_model, serial_number, location,
          installation_date, status, created_at, updated_at,
          report_output_per_hour, setup_minutes, labor_count, power_kw, barcode)
       VALUES (?, ?, ?, ?, ?, ?, ?, 'active', ?, ?, ?, ?, ?, ?, ?)`,
      [
        name, assetId, photoFor('machine', name),
        `${name} · ${area}`, `SN-${assetId}-${between(1000, 9999)}`,
        location, day(at(MONTHS_OF_HISTORY, 2)),
        iso(at(MONTHS_OF_HISTORY, 2)), stamp,
        perHour, setup, labor, kw, `MCH-${assetId}`,
      ],
    );
    machines.push({ id: r.lastID, name, assetId, location });
  }

  const DIES = [
    ['DIE-SW10-A', 'Switch plate 10A blank', 2, 1, 250000],
    ['DIE-SW20-A', 'Switch plate 20A blank', 2, 1, 250000],
    ['DIE-SKT10-B', 'Socket body 10A form', 1, 2, 180000],
    ['DIE-SKT20-B', 'Socket body 20A form', 1, 2, 180000],
    ['DIE-PNT-C', 'Penta faceplate pierce', 4, 1, 400000],
    ['DIE-TRM-D', 'Terminal strip progressive', 6, 1, 500000],
  ];
  const dies = [];
  for (const [toolCode, parts, cavities, strokesPerPiece, maxStrokes] of DIES) {
    // Wear accumulated over the year, deterministic per die.
    const strokes = between(Math.floor(maxStrokes * 0.18), Math.floor(maxStrokes * 0.72));
    const r = await run(
      `INSERT INTO dies
         (tool_code, produced_part_numbers, photo_urls, operational_notes,
          storage_location, number_of_cavities, stroke_count, max_strokes,
          status, ownership, created_at, updated_at, strokes_per_piece,
          setup_minutes)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'active', 'owned', ?, ?, ?, ?)`,
      [
        toolCode, parts,
        JSON.stringify([photoFor('die', toolCode)]),
        'Sharpened at the last preventive-maintenance slot.',
        `Tool room · rack ${pick(['R1', 'R2', 'R3'])}`,
        cavities, strokes, maxStrokes,
        iso(at(MONTHS_OF_HISTORY, 4)), stamp, strokesPerPiece, between(20, 60),
      ],
    );
    dies.push({ id: r.lastID, toolCode, strokes, maxStrokes });
  }

  // Seeded template nodes name their machine loosely — sometimes the machine,
  // sometimes the rack it stands on — so resolve on any of the three.
  const machineByKey = new Map();
  for (const m of machines) {
    for (const key of [m.name, m.assetId, m.location]) {
      if (key) machineByKey.set(String(key).trim().toLowerCase(), m.id);
    }
  }

  // ── Phase 3 · Supply side: vendors and sub-contractors (L0) ──────────────
  phase('Supply side: vendors and sub-contractors');
  const VENDORS = [
    ['Bharat Metals & Alloys', 'BMA', '27AABCB1234C1Z5', 'Bhosari MIDC, Pune', 'Sanjay Rane'],
    ['Deccan Copper Works', 'DCW', '27AACCD5678D1Z9', 'Chakan, Pune', 'Nilesh Waghmare'],
    ['Shree Polymers', 'SPL', '27AADCS9012E1Z3', 'Ranjangaon, Pune', 'Harish Mehta'],
    ['Konark Plating Services', 'KPS', '27AAECK3456F1Z7', 'Hadapsar, Pune', 'Vinod Kadam'],
    ['Vidarbha Packaging', 'VPK', '27AAFCV7890G1Z1', 'Nagpur', 'Suresh Tiwari'],
    ['Precision Tool & Die', 'PTD', '27AAGCP2345H1Z4', 'Pimpri, Pune', 'Ravi Naik'],
  ];
  const vendors = [];
  for (const [name, alias, gst, address, contact] of VENDORS) {
    const r = await run(
      `INSERT INTO vendors
         (name, alias, gst_number, address, contact_name, phone, email,
          logo_url, photo_url, is_archived, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?)`,
      [
        name, alias, gst, address, contact,
        `+9120${between(20000000, 29999999)}`,
        `${alias.toLowerCase()}@vendor.local`,
        photoFor('vendor', name), photoFor('vendor', name),
        iso(at(MONTHS_OF_HISTORY, 6)), stamp,
      ],
    );
    vendors.push({ id: r.lastID, name, alias });
  }

  const clients = await all('SELECT id, name FROM clients ORDER BY id');
  const subContractors = [];
  if (clients.length) {
    for (const [name, phone] of [
      ['Ajinkya Fabrication Works', '+912027551234'],
      ['Samarth Powder Coating', '+912027559876'],
    ]) {
      const r = await run(
        `INSERT INTO sub_contractors
           (client_id, name, phone, email, notes, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        [
          clients[0].id, name, phone, `${name.split(' ')[0].toLowerCase()}@sub.local`,
          'Job-work partner since the first quarter on the system.',
          iso(at(MONTHS_OF_HISTORY - 2, 12)), stamp,
        ],
      );
      subContractors.push({ id: r.lastID, name });
    }
  }

  // ── Phase 4 · Payroll structure and leave policy (L0) ────────────────────
  phase('Payroll structure and leave policy');
  const COMPONENTS = [
    ['Basic', 'earning', 'percent_of_ctc', 0, { percent: 50 }],
    ['House Rent Allowance', 'earning', 'percent_of_basic', 0, { percent: 40 }],
    ['Conveyance Allowance', 'earning', 'fixed', 0, { amount: 1600 }],
    ['Overtime', 'earning', 'per_hour', 0, { rate: 145 }],
    ['Provident Fund', 'deduction', 'percent_of_basic', 1, { percent: 12 }],
    ['Professional Tax', 'deduction', 'fixed', 1, { amount: 200 }],
    ['ESI', 'deduction', 'percent_of_gross', 1, { percent: 0.75 }],
  ];
  const hasPayroll = await tableExists('payroll_components')
    && await tableExists('payroll_runs') && await tableExists('payslips');
  for (const [name, type, method, statutory, config] of (hasPayroll ? COMPONENTS : [])) {
    await run(
      `INSERT INTO payroll_components (name, type, calculation_method, is_statutory, config_json)
       VALUES (?, ?, ?, ?, ?)`,
      [name, type, method, statutory, JSON.stringify(config)],
    );
  }

  const hasLeave = await tableExists('leave_types') && await tableExists('leave_requests');
  const leaveTypeIds = [];
  for (const [name, paid, rule] of (hasLeave ? [
    ['Casual Leave', 1, '12 per year, accrued monthly'],
    ['Sick Leave', 1, '8 per year'],
    ['Earned Leave', 1, '15 per year, carry forward capped at 30'],
    ['Leave Without Pay', 0, 'On approval'],
  ] : [])) {
    const r = await run(
      'INSERT INTO leave_types (name, paid, accrual_rule) VALUES (?, ?, ?)',
      [name, paid, rule],
    );
    leaveTypeIds.push(r.lastID);
  }

  // ── Phase 5 · Bills of material (L1) ─────────────────────────────────────
  phase('Bills of material');
  // Without these an Assembly stage raises a job carrying zero tasks.
  const items = await all('SELECT id, name, unit_id FROM items ORDER BY id');
  const materials = await all(
    'SELECT barcode, name, unit_id FROM materials WHERE kind != ? ORDER BY id LIMIT 40',
    ['parent'],
  );
  let bomLines = 0;
  if (materials.length >= 4) {
    const assembled = items.filter((i) => /switch|socket/i.test(i.name));
    for (const item of assembled) {
      const componentCount = between(3, 5);
      for (let k = 0; k < componentCount; k += 1) {
        const mat = materials[(item.id * 7 + k * 3) % materials.length];
        await run(
          `INSERT INTO item_bom_lines
             (item_id, material_barcode, material_name, quantity_per_unit,
              wastage_percent, unit_id, sort_order, created_at, updated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
          [
            item.id, mat.barcode, mat.name,
            Number((0.5 + rng() * 3).toFixed(3)),
            Number((rng() * 4).toFixed(2)),
            mat.unit_id || item.unit_id, k,
            iso(at(MONTHS_OF_HISTORY - 1, 8)), stamp,
          ],
        );
        bomLines += 1;
      }
    }
  }

  // ── Phase 6 · Eleven months of order book (L2) ───────────────────────────
  phase('Eleven months of order book');
  // Volume ramps: the business won work as the year went on.
  const HSN = ['85365020', '85366990', '85044090', '94054090'];
  const orderRows = [];
  let orderSeq = 1000;
  for (let m = MONTHS_OF_HISTORY; m >= 0; m -= 1) {
    const monthsIn = MONTHS_OF_HISTORY - m;
    // 3 lines/month at the start, ~11 by the end.
    const lineCount = Math.max(3, Math.round(3 + monthsIn * 0.8));
    // Early months only had the first two clients on the books.
    const clientPool = clients.slice(0, Math.min(clients.length, 2 + Math.floor(monthsIn / 2)));
    for (let n = 0; n < lineCount && clientPool.length; n += 1) {
      orderSeq += 1;
      const client = pick(clientPool);
      const item = pick(items);
      const placed = at(m, between(1, 27));
      const orderNo = `ORD-${orderSeq}`;
      const qty = between(2, 40) * 25;
      const unitPrice = Number((45 + rng() * 380).toFixed(2));
      const taxable = Number((qty * unitPrice).toFixed(2));
      const gst = Number((taxable * 0.09).toFixed(2));
      // Values must match the client's OrderStatus enum
      // {draft, notStarted, inProgress, completed, delayed} — anything else
      // silently falls back to notStarted in the app.
      // Older work has run its course; recent work is still live, and a couple
      // of the older-but-open lines are genuinely late.
      const status = m >= 2
        ? (rng() > 0.94 ? 'delayed' : 'completed')
        : (m === 1 ? pick(['inProgress', 'inProgress', 'completed']) : pick(['notStarted', 'inProgress']));
      const end = new Date(placed); end.setDate(end.getDate() + between(12, 45));

      await run(
        `INSERT OR IGNORE INTO order_headers (order_no, client_id, po_number, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?)`,
        [orderNo, client.id, `PO/${client.name.slice(0, 3).toUpperCase()}/${orderSeq}`, iso(placed), iso(placed)],
      );
      const r = await run(
        `INSERT INTO order_items
           (order_no, client_id, client_name, po_number, item_id, item_name,
            variation_leaf_node_id, quantity, unit_id, unit_name, unit_symbol,
            unit_price, total_invoiced_qty, status, created_at, updated_at,
            start_date, end_date, hsn_code, taxable_value, cgst_rate, sgst_rate,
            cgst_amount, sgst_amount)
         VALUES (?, ?, ?, ?, ?, ?, 0, ?, ?, 'Piece', 'Pc', ?, ?, ?, ?, ?, ?, ?, ?, ?, 9, 9, ?, ?)`,
        [
          orderNo, client.id, client.name,
          `PO/${client.name.slice(0, 3).toUpperCase()}/${orderSeq}`,
          item.id, item.name, qty, item.unit_id || 3, unitPrice,
          status === 'completed' ? qty : Math.floor(qty * rng() * 0.6),
          status, iso(placed), iso(placed), day(placed), day(end),
          pick(HSN), taxable, gst, gst,
        ],
      );
      orderRows.push({
        id: r.lastID, orderNo, clientId: client.id, clientName: client.name,
        itemId: item.id, itemName: item.name, qty, placed, status, monthsAgo: m,
      });
    }
  }

  // ── Phase 7 · Production runs against the seeded pipelines (L3) ──────────
  phase('Production runs against the seeded pipelines');
  const templates = await all('SELECT id, version, nodes_json FROM pipeline_templates');
  const runs = [];
  let machineAssignments = 0;
  if (templates.length) {
    for (const order of orderRows) {
      // Roughly three in four order lines actually went to the floor.
      if (rng() > 0.74) continue;
      const tpl = pick(templates);
      let nodes = [];
      try { nodes = JSON.parse(tpl.nodes_json || '[]'); } catch { nodes = []; }
      if (!nodes.length) continue;

      const started = new Date(order.placed);
      started.setDate(started.getDate() + between(1, 6));
      const isDone = order.status === 'completed';
      const completed = isDone ? new Date(started.getTime() + between(2, 12) * 86400000) : null;

      const nodeStatus = {};
      const nodeMetrics = {};
      const batchQty = {};
      nodes.forEach((node, idx) => {
        const done = isDone || idx < Math.max(1, Math.floor(nodes.length * 0.6));
        nodeStatus[node.id] = done ? 'completed' : (idx === Math.floor(nodes.length * 0.6) ? 'active' : 'queued');
        batchQty[node.id] = order.qty;
        if (done) {
          const scrap = Math.floor(order.qty * (0.005 + rng() * 0.03));
          nodeMetrics[node.id] = {
            allotted: order.qty,
            output: order.qty - scrap,
            scrap,
            goodYield: Number((((order.qty - scrap) / order.qty) * 100).toFixed(2)),
          };
        }
      });

      const runId = `run-${order.orderNo.toLowerCase()}-${tpl.id}`;
      await run(
        `INSERT OR IGNORE INTO pipeline_runs
           (id, template_id, template_version, name, status, overrides_json,
            node_status_json, started_at, completed_at, created_at,
            scrap_routing, node_metrics_json, created_by, weight_kg)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'inventory', ?, 'seed', ?)`,
        [
          runId, tpl.id, tpl.version || 1,
          `${order.itemName} · ${order.orderNo}`,
          // planned/in_progress/paused are what the machine queue and the
          // active-run rollups select on; 'active' is a fourth convention in
          // this column that nothing reads.
          isDone ? 'completed' : 'in_progress',
          JSON.stringify({
            actualDurationHoursByNode: {},
            batchQuantityByNode: batchQty,
            machineOverrideByNode: {},
          }),
          JSON.stringify(nodeStatus), iso(started),
          completed ? iso(completed) : null, iso(started),
          JSON.stringify(nodeMetrics),
          Number((order.qty * 0.045).toFixed(2)),
        ],
      );
      runs.push({ id: runId, order, nodes, nodeMetrics });
      runByOrderId.add(order.id);

      await run(
        `INSERT INTO order_pipeline_assignments (order_item_id, pipeline_run_id, allocated_quantity, created_at)
         VALUES (?, ?, ?, ?)`,
        [order.id, runId, order.qty, iso(started)],
      );

      // The machine-queue battery reads run_machine_assignments first and only
      // falls back to matching node strings. Writing the link makes each
      // machine's load explicit instead of accidental.
      for (let n = 0; n < nodes.length; n += 1) {
        const node = nodes[n];
        // Input/Output are endpoints, not work — they occupy no machine.
        if (node.processType === 'Input' || node.processType === 'Output') continue;
        // A run that is still going occupies exactly the stage it is on, so
        // only that stage sits in a machine's queue. Finished runs record every
        // stage they used — history, and excluded from the queue by status.
        if (!isDone && nodeStatus[node.id] !== 'active') continue;
        const key = String(node.machine || '').trim().toLowerCase();
        // Honour the fixture's machine where it names one; otherwise put the
        // stage on a machine deterministically, so load spreads across the
        // floor instead of piling onto the two the fixtures happen to mention.
        const machineId = (key && machineByKey.get(key))
          || machines[(order.id + n) % machines.length]?.id;
        if (!machineId) continue;
        await run(
          `INSERT OR IGNORE INTO run_machine_assignments
             (run_id, node_id, machine_id, created_at)
           VALUES (?, ?, ?, ?)`,
          [runId, node.id, machineId, iso(started)],
        );
        machineAssignments += 1;
      }

      // Floor reconciliation per finished stage — what Insights reads.
      for (const [nodeId, met] of Object.entries(nodeMetrics)) {
        await run(
          `INSERT OR IGNORE INTO stage_reconciliations
             (run_id, node_id, allotted, output, leftover, scrap, good_yield,
              actual_hours, leftover_action, updated_at)
           VALUES (?, ?, ?, ?, 0, ?, ?, ?, 'inventory', ?)`,
          [runId, nodeId, met.allotted, met.output, met.scrap, met.goodYield,
           Number((1 + rng() * 6).toFixed(2)), iso(completed || started)],
        );
      }
    }
  }

  // ── Phase 8 · Challans: goods went out, material came in (L3) ────────────
  phase('Challans: goods went out, material came in');
  // created_by/updated_by on a challan are foreign keys into users, not free
  // text — resolve a real account to stamp the year's paperwork with.
  const seedUser = await get(
    "SELECT id FROM users ORDER BY CASE WHEN role='super_admin' THEN 0 ELSE 1 END, id LIMIT 1");
  const byUser = seedUser?.id ?? null;

  let challanSeq = 500;
  let receptionSeq = 300;
  const challans = [];
  for (const order of orderRows) {
    if (order.status !== 'completed' && rng() > 0.35) continue;
    challanSeq += 1;
    const dispatched = new Date(order.placed);
    dispatched.setDate(dispatched.getDate() + between(6, 30));
    const r = await run(
      `INSERT INTO delivery_challans
         (challan_no, date, customer_name, notes, status, created_by, created_at,
          updated_at, order_no, type, maintain_stocks, used_in_report, purpose)
       VALUES (?, ?, ?, ?, 'issued', ?, ?, ?, ?, 'delivery', 1, 1, 'sale')`,
      [
        `SU-DEL-${challanSeq}`, day(dispatched), order.clientName,
        `Against ${order.orderNo}`, byUser, iso(dispatched), iso(dispatched), order.orderNo,
      ],
    );
    await run(
      `INSERT INTO delivery_challan_items
         (challan_id, order_item_id, item_id, line_no, particulars, quantity_pcs,
          weight, created_at, updated_at, variation_leaf_node_id)
       VALUES (?, ?, ?, 1, ?, ?, ?, ?, ?, 0)`,
      [
        r.lastID, order.id, order.itemId, order.itemName, order.qty,
        Number((order.qty * 0.045).toFixed(3)), iso(dispatched), iso(dispatched),
      ],
    );
    challans.push({ id: r.lastID, type: 'delivery' });
  }

  // Inward material against vendors, roughly twice a month.
  for (let m = MONTHS_OF_HISTORY; m >= 0; m -= 1) {
    for (let k = 0; k < 2; k += 1) {
      receptionSeq += 1;
      const vendor = pick(vendors);
      const received = at(m, 5 + k * 14);
      const r = await run(
        `INSERT INTO delivery_challans
           (challan_no, date, notes, status, created_by, created_at, updated_at,
            type, vendor_id, vendor_name, maintain_stocks, used_in_report, purpose)
         VALUES (?, ?, ?, 'issued', ?, ?, ?, 'reception', ?, ?, 1, 1, 'purchase')`,
        [
          `SU-REC-${receptionSeq}`, day(received),
          `Inward from ${vendor.name}`, byUser, iso(received), iso(received),
          vendor.id, vendor.name,
        ],
      );
      challans.push({ id: r.lastID, type: 'reception' });

      if (materials.length) {
        const mat = pick(materials);
        const qty = between(200, 2500);
        await run(
          `INSERT INTO inventory_movements
             (material_barcode, movement_type, qty, reason_code, reference_type,
              reference_id, actor, created_at, source_challan_id,
              source_challan_type, primary_qty)
           VALUES (?, 'in', ?, 'purchase', 'challan', ?, 'seed', ?, ?, 'reception', ?)`,
          [mat.barcode, qty, String(r.lastID), iso(received), r.lastID, qty],
        );
      }
    }
  }

  // ── Phase 9 · Procurement requests (L3) ──────────────────────────────────
  phase('Procurement requests');
  let procSeq = 100;
  let procLines = 0;
  for (let m = MONTHS_OF_HISTORY; m >= 0; m -= 2) {
    procSeq += 1;
    const vendor = pick(vendors);
    const raised = at(m, between(3, 20));
    const isOpen = m <= 1;
    const r = await run(
      `INSERT INTO procurement_requests
         (request_number, supplier_name, status, expected_date, notes,
          created_by_name, created_by_role, raised_by_name, raised_by_role,
          raised_at, closed_at, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, 'Rohit Sawant', 'Stores & Purchase',
               'Rohit Sawant', 'Stores & Purchase', ?, ?, ?, ?)`,
      [
        `PR-${procSeq}`, vendor.name, isOpen ? 'raised' : 'closed',
        day(new Date(raised.getTime() + 10 * 86400000)),
        'Replenishment against consumption forecast.',
        iso(raised), isOpen ? null : iso(new Date(raised.getTime() + 9 * 86400000)),
        iso(raised), stamp,
      ],
    );
    // (request, material) is unique — draw distinct materials per request.
    const lineMaterials = [];
    const poolCopy = materials.slice();
    for (let k = 0; k < between(2, 4) && poolCopy.length; k += 1) {
      lineMaterials.push(poolCopy.splice(Math.floor(rng() * poolCopy.length), 1)[0]);
    }
    for (const mat of lineMaterials) {
      const reqQty = between(100, 1800);
      const recvQty = isOpen ? Math.floor(reqQty * rng() * 0.5) : reqQty;
      await run(
        `INSERT INTO procurement_request_lines
           (procurement_request_id, material_barcode, material_name, requested_qty,
            received_qty, pending_qty, unit_id, status, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          r.lastID, mat.barcode, mat.name, reqQty, recvQty, reqQty - recvQty,
          mat.unit_id, isOpen ? 'partial' : 'received', iso(raised), stamp,
        ],
      );
      procLines += 1;
    }
  }

  // ── Phase 10 · Assembly jobs handed to workers (L4) ──────────────────────
  phase('Assembly jobs handed to workers');
  let batchSeq = 0;
  let jobCount = 0;
  let taskCount = 0;
  const assemblyRuns = runs.filter((r) =>
    r.nodes.some((n) => /assembly|rivet/i.test(`${n.processType} ${n.name}`)));
  for (const r of assemblyRuns.slice(0, 26)) {
    const node = r.nodes.find((n) => /assembly|rivet/i.test(`${n.processType} ${n.name}`));
    const created = new Date(r.order.placed);
    created.setDate(created.getDate() + between(3, 10));
    const settled = r.order.status === 'completed';

    let batchId = null;
    if (settled || rng() > 0.4) {
      batchSeq += 1;
      const b = await run(
        `INSERT INTO freelancer_job_batches
           (freelancer_id, batch_number, status, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?)`,
        [null, `BATCH-${1000 + batchSeq}`, settled ? 'completed' : 'assigned',
         iso(created), iso(created)],
      );
      batchId = b.lastID;
    }
    const j = await run(
      `INSERT INTO freelancer_jobs
         (batch_id, run_id, node_id, item_id, variation_leaf_node_id, quantity,
          status, payout_balance, created_at, updated_at)
       VALUES (?, ?, ?, ?, 0, ?, ?, ?, ?, ?)`,
      [
        batchId, r.id, node.id, r.order.itemId, r.order.qty,
        settled ? 'completed' : (batchId ? 'in_progress' : 'pending'),
        settled ? Number((r.order.qty * 1.75).toFixed(2)) : 0,
        iso(created), stamp,
      ],
    );
    jobCount += 1;
    const bom = await all('SELECT * FROM item_bom_lines WHERE item_id = ?', [r.order.itemId]);
    for (const line of bom) {
      const mat = await get(
        'SELECT linked_item_id, linked_variation_leaf_node_id FROM materials WHERE barcode = ?',
        [line.material_barcode],
      );
      if (!mat?.linked_item_id) continue;
      await run(
        `INSERT INTO freelancer_job_tasks
           (job_id, item_id, variation_leaf_node_id, required_quantity, status,
            created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        [
          j.lastID, mat.linked_item_id, mat.linked_variation_leaf_node_id || 0,
          Number((line.quantity_per_unit * r.order.qty * (1 + line.wastage_percent / 100)).toFixed(3)),
          settled ? 'completed' : 'pending', iso(created), stamp,
        ],
      );
      taskCount += 1;
    }
  }

  // ── Phase 11 · Eleven closed payroll cycles + leave history (L4) ─────────
  phase('Eleven closed payroll cycles + leave history');
  let payslipCount = 0;
  if (!hasPayroll) skipped.push('payroll (tables absent on this database)');
  for (let m = hasPayroll ? MONTHS_OF_HISTORY : 0; m >= 1; m -= 1) {
    const when = at(m, 28, 18);
    const headcount = employees.filter((_, i) => i < STAFF.length - (m > 8 ? 4 : 0));
    const gross = headcount.reduce((s, e) => s + (e.employment === 'contract' ? 18000 : 32000), 0);
    const deduction = Math.round(gross * 0.145);
    const pr = await run(
      `INSERT INTO payroll_runs
         (client_id, month, year, status, processed_at, total_gross, total_deduction, total_net)
       VALUES (?, ?, ?, 'processed', ?, ?, ?, ?)`,
      [
        clients[0]?.id ?? null, when.getMonth() + 1, when.getFullYear(),
        iso(when), gross, deduction, gross - deduction,
      ],
    );
    for (const e of headcount) {
      await run(
        'INSERT INTO payslips (run_id, employee_id, pdf_path) VALUES (?, ?, ?)',
        [pr.lastID, e.id, `payslips/${when.getFullYear()}-${when.getMonth() + 1}/${e.id}.pdf`],
      );
      payslipCount += 1;
    }
  }

  let leaveCount = 0;
  if (!hasLeave) skipped.push('leave requests (tables absent on this database)');
  for (let i = 0; i < (hasLeave ? 28 : 0); i += 1) {
    const e = pick(employees);
    const from = at(between(0, MONTHS_OF_HISTORY), between(1, 26));
    const days = between(1, 4);
    const to = new Date(from.getTime() + (days - 1) * 86400000);
    await run(
      `INSERT INTO leave_requests
         (employee_id, leave_type_id, from_date, to_date, days, reason, status, created_at, decided_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        e.id, pick(leaveTypeIds), day(from), day(to), days,
        pick(['Family function', 'Medical', 'Personal work', 'Travel']),
        pick(['approved', 'approved', 'approved', 'rejected']),
        iso(from), iso(from),
      ],
    );
    leaveCount += 1;
  }

  // ── Phase 12 · Catalogue imagery on the shared masters ───────────────────
  phase('Catalogue imagery');
  // Items, clients and sets are created by the base seed, so their pictures are
  // attached here rather than at insert. Matched on name, and only set when the
  // generated file for that name exists — a rename should leave the tile blank
  // rather than point at a 404.
  const fs = require('fs');
  const path = require('path');
  const seedImageDir = path.join(__dirname, '..', '..', 'public', 'seed');
  let available = new Set();
  try {
    available = new Set(fs.readdirSync(seedImageDir));
  } catch {
    console.warn('[scenario:established] no generated imagery —'
      + ' run tools/generate-seed-images.py');
  }
  const photoIfPresent = (domain, name) => {
    const file = `${domain}-${imageSlug(name)}.png`;
    return available.has(file) ? `${IMAGE_BASE}/${file}` : null;
  };

  let imagesAttached = 0;
  let imagesMissing = 0;
  const attach = async (table, column, rows, domain, extraColumn) => {
    for (const row of rows) {
      const url = photoIfPresent(domain, row.name);
      if (!url) {
        imagesMissing += 1;
        continue;
      }
      const sets = extraColumn
        ? `${column} = ?, ${extraColumn} = ?`
        : `${column} = ?`;
      const params = extraColumn ? [url, url, row.id] : [url, row.id];
      await run(`UPDATE ${table} SET ${sets} WHERE id = ?`, params);
      imagesAttached += 1;
    }
  };

  await attach('items', 'photo_url',
    await all('SELECT id, name FROM items'), 'item');
  await attach('clients', 'photo_url',
    await all('SELECT id, name FROM clients'), 'client', 'logo_url');
  // A set's picture lives in uploaded_assets (entity_type 'inventory_set'),
  // which is what the Sets card resolves — so it is registered, not column-set.
  for (const set of await all('SELECT id, name FROM inventory_sets')) {
    const file = `set-${imageSlug(set.name)}.png`;
    if (!available.has(file)) { imagesMissing += 1; continue; }
    await run(
      `INSERT INTO uploaded_assets
         (entity_type, entity_id, file_name, content_type, size_bytes, sha256,
          object_key, status, is_primary, created_at, uploaded_at)
       VALUES ('inventory_set', ?, ?, 'image/png', 0, '', ?, 'uploaded', 1, ?, ?)`,
      [set.id, file, `public/seed/${file}`, stamp, stamp],
    );
    imagesAttached += 1;
  }

  summary.imagesAttached = imagesAttached;
  if (imagesMissing) summary.imagesMissing = imagesMissing;

  // ── Phase 13 · The paper trail on each order (L3) ────────────────────────
  phase('Order status history and activity');
  // What the order's Track view reads. Both tables key on order_items.id — the
  // order LINE, not the header — which is what the dialog passes in.
  let statusRows = 0;
  let activityRows = 0;
  const office = employees.filter((e) => e.dept === 'Accounts & Admin');
  const dispatch = employees.filter((e) => e.dept === 'Quality & Dispatch');
  const actorFor = (pool) => {
    const person = pool.length ? pick(pool) : null;
    return person ?? { name: 'Super Admin', role: 'Administrator' };
  };

  for (const order of orderRows) {
    const placed = order.placed;
    const day2 = new Date(placed.getTime() + between(1, 4) * 86400000);
    const day3 = new Date(placed.getTime() + between(6, 26) * 86400000);

    // Status trail: every order starts notStarted; how far it went depends on
    // where it ended up, so the trail agrees with the row's current status.
    const trail = [[null, 'notStarted', placed]];
    if (order.status !== 'notStarted') {
      trail.push(['notStarted', 'inProgress', day2]);
    }
    if (order.status === 'completed' || order.status === 'delayed') {
      trail.push(['inProgress', order.status, day3]);
    }
    for (const [from, to, when] of trail) {
      await run(
        `INSERT INTO order_status_history
           (order_id, previous_status, new_status, changed_by_user_id, changed_at)
         VALUES (?, ?, ?, ?, ?)`,
        [order.id, from, to, byUser, iso(when)],
      );
      statusRows += 1;
    }

    // Activity: the handful of moves that actually leave a trace on an order.
    const clerk = actorFor(office);
    const shipper = actorFor(dispatch);
    const activity = [
      ['order_created', 'order_form', clerk, placed],
      ['item_added', 'order_form', clerk, placed],
      if_pipeline(order) ? ['pipeline_assigned', 'production', shipper, day2] : null,
      order.status === 'completed'
        ? ['challan_issued', 'challan_form', shipper, day3]
        : null,
      order.status === 'delayed'
        ? ['due_date_missed', 'system', clerk, day3]
        : null,
    ].filter(Boolean);
    for (const [type, source, actor, when] of activity) {
      await run(
        `INSERT INTO order_activity_log
           (order_id, activity_type, actor_user_id, actor_name, actor_role,
            source, details_json, created_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          order.id, type, null, actor.name, actor.role, source,
          JSON.stringify({ orderNo: order.orderNo, item: order.itemName }),
          iso(when),
        ],
      );
      activityRows += 1;
    }
  }

  summary.statusHistory = statusRows;
  summary.orderActivity = activityRows;

  summary.departments = DEPARTMENTS.length;
  summary.employees = employees.length;
  summary.machines = machines.length;
  summary.dies = dies.length;
  summary.vendors = vendors.length;
  summary.subContractors = subContractors.length;
  summary.bomLines = bomLines;
  summary.orderLines = orderRows.length;
  summary.pipelineRuns = runs.length;
  summary.machineAssignments = machineAssignments;
  summary.challans = challans.length;
  summary.procurementLines = procLines;
  summary.freelancerJobs = jobCount;
  summary.freelancerTasks = taskCount;
  summary.payslips = payslipCount;
  summary.leaveRequests = leaveCount;
  summary.inventoryMovements = await countOf('inventory_movements');
  if (skipped.length) summary.skipped = skipped;

  console.log('[scenario:established] seeded a year of operations —',
    JSON.stringify(summary));
  return summary;
};
